UID_KEY = "uid"
TOKEN_KEY = "token"
COURSE_CODE_KEY = "course_codes"
LOGIN_URL = "https://hello.iitk.ac.in/index.php/user/login"
API_URL = "https://hello.iitk.ac.in/api/"
COURSES_DIV_ID = "block-views-block-courses-block-1"
